<?php


namespace app\middleware\privilege;


use app\common\facade\ErrCode as ErrCodeFacade;
use app\common\logic\Merchant as MerchantLogic;
use app\common\model\ApiCommunicant as ApiCommunicantModel;
use app\common\Request;
use app\common\util\JsonTable;
use app\middleware\Base;

class MerchantInfo extends Base
{
    protected function before(Request $request): JsonTable
    {
        $appid = $this->request->get('appid');
        $api = ApiCommunicantModel::where('ac_appid', $appid)->find();
        if (is_null($api)) {
            return ErrCodeFacade::getJError(25, ['name' => '商户信息']);
        }
        //检查商户是否正常
        $merchant = \throwifJError(MerchantLogic::instance()->checkState($api->ac_merchant));
        //商户信息
        $this->request->merchant = [
            'mch_id' => $merchant->data->mch_id,
            'mch_acquirer' => $merchant->data->mch_acquirer,
            'mch_code' => $merchant->data->mch_code,
        ];
        return parent::before($request); // TODO: Change the autogenerated stub
    }
}